services:
  chromaDb:
    image: chromadb/chroma:latest
    ports:
      - 8000:8000
    environment:
      - CHROMA_SERVER_PORT=8000
    volumes:
      - chroma-db:/chroma 

volumes:
  chroma-db:
    driver: local
